### ISSUE TITLE
I need the pre trained model, what's your email address

### ISSUE THREAD

**Issue by voyager0003** [zaidbhat1234/Image2StyleGAN#1]
Thanks for implementing the paper, its really confused me for a week.
I need the pre trained model but i cannot found your email

**Comment by zaidbhat1234** [comment]
I will share it over the weekend. Just give me a couple of days. @vegetable09

**Comment by voyager0003** [comment]
Thanks! I will try myself to work it around first

And your ipynb file is well commented, for me, it's a great material to learn

**Comment by zaidbhat1234** [comment]
Sure. If you do need it just tell me how I should share it with you. 

Regards
Zaid Pervaiz Bhat
National Institute of Technology, Srinagar
+91 7006338911

**Comment by voyager0003** [comment]
I success convert it from the NVIDIA tf weights : )

**Comment by Yu20010** [comment]
Hi, Zaid. I need the pre-trained model as well.
What is your email address?

**Comment by zaidbhat1234** [comment]
I have updated the Link to the pre-trained model in the ReadMe. Let me know if you can access it.

**Comment by zaidbhat1234** [comment]
@Yu20010

**Comment by zaidbhat1234** [comment]
Hi,

I have updated the link to the pre-trained model.
