### ISSUE TITLE
Where can I get the obama and other people in the demo?

### ISSUE THREAD

**Issue by voyager0003** [zaidbhat1234/Image2StyleGAN#2]
Thanks for your great reimplement first!
And where can I get the obama and other people in the demo?

**Comment by zaidbhat1234** [comment]
Hi,
Thanks. Do star the repo if you like it. I have 2 more repos on similar topics. 
Those images were shared to me when I was interning with KAUST. I am not sure if I am allowed to share them. I will have to check. Thanks!
